steps:
  # Step 1: Build the Docker image for the Spring Boot app
  - name: 'us-central1.pkg.dev/cloud-builders/docker'
    args: ['build', '-t', 'us-central1.pkg.dev/$PROJECT_ID/booknote', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'us-central1.pkg.dev/cloud-builders/docker'
    args: ['push', 'us-central1.pkg.dev/$PROJECT_ID/booknote']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'us-central1.pkg.dev/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'booknote', '--image', 'us-central1.pkg.dev/$PROJECT_ID/booknote', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
options:
  logging: NONE

# Optional: Specify substitutions (if needed)
substitutions:
  _SERVICE_NAME: 'booknote'

# Optional: Define where the artifacts will be stored (if needed)
artifacts:
  images:
    - 'us-central1.pkg.dev/$PROJECT_ID/booknote'
